In [1]:
import numpy as np

a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [2]:
print(a.shape)

(3,)


In [3]:
print(a[0], a[1], a[2])

1 2 3


In [4]:
a[0] = 5
print(a)

[5 2 3]


In [5]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [6]:
print(b[0,0], b[0,1], b[1,0])

1 2 4


In [7]:
a = np.zeros((2,2)) #모두 0으로 된 array 생성
print(a)

[[0. 0.]
 [0. 0.]]


In [8]:
b = np.ones((1,2)) #모두 1로 된 array 생성
print(b)

[[1. 1.]]


In [9]:
c = np.full((2,2),7) #7로 된 array 생성
print(c)

[[7 7]
 [7 7]]


In [10]:
d = np.eye(2) #2X2 matrix 만들기
print(d)

[[1. 0.]
 [0. 1.]]


In [11]:
e = np.random.random((2,2)) #random values로 채우기
print(e)

[[0.74415185 0.92805898]
 [0.72842193 0.41589545]]
