In [3]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype = np.float64)
y = np.array([[5,6],[7,8]], dtype = np.float64)

print(x)

[[1. 2.]
 [3. 4.]]


In [2]:
print(y)

[[5. 6.]
 [7. 8.]]


In [4]:
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [5]:
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


In [6]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [7]:
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


In [8]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [9]:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [10]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [11]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

In [13]:
print(v.dot(w)) #dot is to compute inner products of vectors
print(np.dot(v,w)) #Inner product of vectors; both produce 219

219
219


In [14]:
#Matrix / vector product; both produce the rank 1 array
print(x.dot(v)) 
print(np.dot(x,v))

[29 67]
[29 67]


In [15]:
#Matrix / vector product; both produce the rank 2 array 
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [16]:
x = np.array([[1,2],[3,4]])

In [17]:
print(np.sum(x)) #Compute sum of all elements; prints "10"
print(np.sum(x, axis = 0)) #Compute sum of each column; 1+4, 2+4
print(np.sum(x, axis = 1)) #Compute sum of each row; 1+2, 3+4

10
[4 6]
[3 7]


In [18]:
print(x)

[[1 2]
 [3 4]]


In [19]:
print(x.T)

[[1 3]
 [2 4]]


In [20]:
v = np.array([1,2,3])
print(v)
print(v.T)

[1 2 3]
[1 2 3]
