<a href="https://colab.research.google.com/github/sokim0991/ml-basic-tutorial/blob/main/Numpy_Reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. 배열과 차원을 변형해주는 reshape**

## **1-1. 1차원과 2차원 변환**

In [1]:
import numpy as np
a = [1,2,3,4,5,6,7,8]

#np.reshape(변경할 배열, 차원)
b = np.reshape(a,(2,4))
c = np.reshape(a,(4,2))

In [8]:
#배열.reshape(차원)
print(a.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]


In [2]:
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **1-2. 3차원 변환**

In [4]:
a = np.arange(1,9)

In [5]:
print(a)

[1 2 3 4 5 6 7 8]


In [6]:
b = a.reshape(2,2,2)

In [7]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
b[0]

array([[1, 2],
       [3, 4]])

In [10]:
b[0][0,1]

2

# **2. reshape에서 -1의 의미**

reshape()의 ‘-1’이 의미하는 바는, 변경된 배열의 ‘-1’ 위치의 차원은 “원래 배열의 길이와 남은 차원으로 부터 추정”이 된다는 뜻이다.

In [11]:
x = np.arange(12)
x = x.reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## **2-1. reshape(-1,정수) : 행의 위치에 -1인 경우**


In [12]:
x.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [13]:
x.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [14]:
x.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

즉, 행(row)의 위치에 -1을 넣고 열의 값을 지정해주면 변환될 배열의 행의 수는 알아서 지정이 된다.

## **2-2. reshape(정수,-1) : 열의 위치에 -1인 경우**

In [15]:
x.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [16]:
x.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [17]:
x.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
x.reshape(4,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## **2-3. reshape(-1)인 경우**

In [20]:
x.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
x.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

-1만 들어가면 1차원 배열을 반환한다. 모양상 x.reshape(1,-1)과 같으나 이는 (1,12)인 2차원 배열이다.(대괄호의 수로 확인 가능하다.)

출처 : https://yganalyst.github.io/data_handling/memo_5/