In [11]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[0,1]) #2 출력

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


In [6]:
b = a[:2, 1:3] #[:2]는 앞에 두 배열만 출력 
print(b)

[[2 3]
 [6 7]]


In [7]:
b[0,0] = 77 #2를 77로 바꿈
print (b)

[[77  3]
 [ 6  7]]


In [9]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

row_r1 = a[1,:]   #Rank 1 view of the second row of a
row_r2 = a[1:2,:] #Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [12]:
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [14]:
a = np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])

[1 4 5]


In [15]:
print(a[[0,0],[1, 1]])

[2 2]


In [18]:
print(np.array([a[0,1], a[0,1]]))

[2 2]


In [22]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
b = np.array([0,2,0,1])
print(a[np.arange(4),b])

[ 1  6  7 11]


In [26]:
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [28]:
a = np.array([[1,2], [3,4], [5,6]])

#Find the elements that are bigger than 2

bool_idx = (a > 2)

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [30]:
print(a[a>2])

[3 4 5 6]
