<a href="https://colab.research.google.com/github/sokim0991/ml-basic-tutorial/blob/main/NumPy_np_sum_axis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#reshape(2,3,4)는
#가장 바깥쪽 괄호안에 2개의 원소가 존재하며
#중간 괄호 안에는 3개의 원소가 존재하고
#가장 안쪽 괄호안에는 4개의 원소가 존재한다는 의미입니다.
a = np.arange(24).reshape(2,3,4)

In [2]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [3]:
#axis를 명시하지 않으면 배열에 속하는 모든 원소에 대한 합을 구합니다. 
np.sum(a)

276

In [6]:
#axis=0이면 첫번째 괄호가 사라졌을 때 남은 2차원 원소가 하나로 더해집니다.
#2차원 배열의 대응하는 원소끼리 더하면 됩니다.
np.sum(a, axis=0)
#0+12=12, 1+13=14...

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [7]:
#axis=1이면 두번째 괄호가 사라지면서 남는 1차원 원소가 하나로 더해집니다. 
#예제에선 위에 3개의 1차원 배열의 대응하는 원소끼리 더해서 하나의 1차원 배열이 되고 
#아래에 3개의 1차원 배열의 대응하는 원소끼리 더해서 하나의 1차원 배열이 됩니다. 
np.sum(a, axis=1)
#0+4+8=12, 1+5+9=15...

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [8]:
#axis=2이면 3번째 괄호가 사라지면서 남는 스칼라 원소가 하나로 더해집니다. 
np.sum(a, axis=2)
#0+1+2+3=6, 4+5+6+7=22...

array([[ 6, 22, 38],
       [54, 70, 86]])

In [9]:
#axis=(0,1)이면 첫번째, 두번째 괄호가 사라지면서 남는 1차원 배열의 대응하는 원소끼리 더해집니다. 
np.sum(a, axis=(0,1))
#0+4+8+12+16+20 = 60

array([60, 66, 72, 78])

In [10]:
#axis = (1,2)이면 두번째, 세번째 괄호가 사라지면서 남는 스칼라가 모두 더해집니다. 
np.sum(a, axis=(1,2))
#sum(0,  1,  2,  3, 4,  5,  6,  7, 8,  9, 10, 11) = 66...

array([ 66, 210])